# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Brand' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Brand
pod ‘Alamofire’
pod ‘SwiftyJSON’

  target 'BrandTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BrandUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
